### ISSUE TITLE
Ubuntu可执行的客户端需要的一些函数

### ISSUE THREAD

**Issue by wolfbrother** [EdgeIntelligenceChain/EdgeHand#4]
#### 函数的名称、参数和返回值可以按下面的形式，仅供参考。

+ 根据钱包文件wallet.dat初始化钱包并获得钱包参数
   + 参考EdgenceChain/wallet/Wallet.py的init_wallet函数
+ 查询某个地址的余额
   + 参考Actions.Balance4Addr
      > def getBalance4Addr(str: addr) -> int
+ 查询某个地址的所有UTXO集合
   + 参考Actions.UTXO4Addr
      > def getUTXO4Addr(str: addr)->int
+ 发送交易
   + 参考 https://github.com/jamesob/tinychain/blob/master/client.py
       > def sendTransaction(args)->bool
+ 根据交易ID查询交易状态
   + 参考Actions.TxStatusReq
       > def getTxStatus(str: txid) 

也可参考 https://github.com/jamesob/tinychain/blob/master/client.py
+ 不采用它的参数方面的技巧（docopt库）

**Comment by wolfbrother** [comment]
也可参考 https://github.com/jamesob/tinychain/blob/master/client.py

**Comment by wolfbrother** [comment]
#### 基于socket的同步通信
 + 以 https://blog.csdn.net/su_bao/article/details/80380465 中的客户端的实现为例：
```python
建立网络连接
tcpCliSock = socket(AF_INET,SOCK_STREAM)
tcpCliSock.connect(ADDR)
# 准备发送的数据data
tcpCliSock.send(data.encode())

# 获得返回数据
data = tcpCliSock.recv(BUFSIZ)

# 关闭网络连接
tcpCliSock.close()
```
上述过程是同步通信的，在通信过程中网络连接一直tcpCliSock保持，有如下好处：
+ client这儿不需要配置监听端口，不需要开启监听线程，实现上比较简单。

#### 基于socket的异步通信
Edgence的节点之间的通信就是异步通信。
+ 以同步区块区块为例：node1需要从node2同步区块，在该过程中，node1相当于客户端，node2相当于服务端。过程如下：
  + node1申请与node2建立连接，然后node1先发送一个BlocksSyncReq信息给node2，接着连接断开。
  + node2启动一个线程，处理该请求，准备要应答的数据。
  + node2申请与node1建立连接，然后node2发送一个BlocksSyncGet信息给node1，里面封装了应答数据，接着连接断开。
   + node2处理所得到的应答数据。
如下特点：
+ 由于前后两个连接是独立的，因此在整个过程中作为服务端的node2需要知道node1的IP和监听端口作为建立第二个连接的参数。
+ 客户端也要像服务端一样，建立监听线程。

#### 同步通信和异步通信对比
同步通信对客户端的实现要简单得多：
+ 客户端不需要把自己的监听端口告诉服务端，因为压根就没有监听过程和监听端口
+ 不需要监听进程，比如上面的同步通信的例子，只需要建立连接、发送请求、接收数据三个过程。

**Comment by wolfbrother** [comment]
### 以def getBalance4Addr(addr: str) -> int 为例:
```python
    peer = random.sample(peerList, 1)[0] # 获得节点信息

   # 如下代码获得本客户端的一个空闲端口
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.bind(("",0))
    s.listen(1)
    port = s.getsockname()[1]
    s.close()

   # 客户端发送请求数据到节点
    message = Message(Actions.Balance4Addr, addr, port)
    print(message, peer, port)
    Utils.send_to_peer(message, peer)

    # 建立监听连接，端口是上面指定的端口
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.bind(('', port))
    s.listen(True)
    conn, addr = s.accept()

  # 接收60秒内的来自对应节点的返回数据
    timeout = time.time() + 60
    while True and time.time() < timeout:
        if addr[0] == peer[0]:
            data = conn.recv(1024)[4:]
            if data: # 如果获得数据，则停止循环
                break
        else:
            pass
    conn.close() # 关闭连接

   #解析所获得数据为Message对象，并返回balance值
    message = Utils.deserialize(data.decode(), gs) 
    return message.data

```

**Comment by wolfbrother** [comment]
> ### 以def getBalance4Addr(addr: str) -> int 为例:
> ```python
>     peer = random.sample(peerList, 1)[0] # 获得节点信息
> 
>    # 如下代码获得本客户端的一个空闲端口
>     s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>     s.bind(("",0))
>     s.listen(1)
>     port = s.getsockname()[1]
>     s.close()
> 
>    # 客户端发送请求数据到节点
>     message = Message(Actions.Balance4Addr, addr, port)
>     print(message, peer, port)
>     Utils.send_to_peer(message, peer)
> 
>     # 建立监听连接，端口是上面指定的端口
>     s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>     s.bind(('', port))
>     s.listen(True)
>     conn, addr = s.accept()
> 
>   # 接收60秒内的来自对应节点的返回数据
>     timeout = time.time() + 60
>     while True and time.time() < timeout:
>         if addr[0] == peer[0]:
>             data = conn.recv(1024)[4:]
>             if data: # 如果获得数据，则停止循环
>                 break
>         else:
>             pass
>     conn.close() # 关闭连接
> 
>    #解析所获得数据为Message对象，并返回balance值
>     message = Utils.deserialize(data.decode(), gs) 
>     return message.data
> ```
> 
> 效果如下：
> 
> > jin@jin-VirtualBox:~/.ssh/EdgeHand$ python3 hand.py
> > [2019-03-14 02:25:26,499][Wallet:58] INFO [wallet] your address is 1M32gppnnKfCcedHq3weaAagKU7Ppt6KFD
> > [2019-03-14 02:25:26,503][Peer:71] INFO [p2p] loading peers with 1 hostnames
> > [2019-03-14 02:25:26,523][Utils:117] INFO [utils] succeed in sending to Peer(ip='127.0.0.1', port=9999) data in 1th time
> > balance is:  470000000000
> 
> #### 说明
> * 上述函数以异步通信的形式实现了同步的过程
> * 上述函数没有考虑到失败的情况，你实现时需要补充异常处理。

以面向对象的形式来作封装，则有：
``` python
class EdgeHand(object):

    def __init__(self, walletFile='mywallet.dat'):

        self.gs = dict()
        self.gs['Block'], self.gs['Transaction'], self.gs['UnspentTxOut'], self.gs['Message'], self.gs['TxIn'], \
            self.gs['TxOut'], self.gs['Peer'] = globals()['Block'], globals()['Transaction'], globals()['UnspentTxOut'],\
                                                globals()['Message'], globals()['TxIn'], globals()['TxOut'], globals()['Peer']

        self.chain_lock = threading.RLock()


        self.wallet = Wallet.init_wallet(walletFile)
        self.peerList = Peer.init_peers(Params.PEERS_FILE)


    def getBalance4Addr(self) -> int:
        with self.chain_lock:
            peer = random.sample(self.peerList, 1)[0]

            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            s.bind(("",0))
            s.listen(1)
            port = s.getsockname()[1]
            s.close()
            message = Message(Actions.Balance4Addr, self.wallet.my_address, port)
            Utils.send_to_peer(message, peer)

            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            s.bind(('', port))
            s.listen(True)
            conn, addr = s.accept()

            timeout = time.time() + 60
            message = None
            while True and time.time() < timeout:
                if addr[0] == peer[0]:
                    message = Utils.read_all_from_socket(conn, self.gs)
                    if message:
                        break
                else:
                    pass
            conn.close()
            return message.data
```

**Comment by wolfbrother** [comment]
### 现状
有你提交的liuying_add_func分支；

以及我提交的有四个分支：
+ master分支
  + 最初的getBalance4Addr的例子，以面向对象的方式实现的钱包
+ demo_exception-wolfbrother分支
  + 在master分支基础上，增加了异常检测
+ merge_failure-wolfbrother分支
  + 合并liuying_add_func并对各个函数做了修改

### 下一步
尽量按merge_failure-wolfbrother分支对函数的接口和封装方式，借鉴demo_exception-wolfbrother的异常检测和处理方式，找出bug并修正。

### 对主节点代码的改动
+ Wallet类的pubkey_to_address(cls, pubkey: bytes) 的返回值的类型问题

目前返回值是str，如果返回值设置为bytes，会不会影响目前节点之间已有的通信。
```python
		sha = hashlib.sha256(pubkey).digest()
		ripe = hashlib.new('ripemd160', sha).digest()
		return str(b58encode_check(b'\x00' + ripe))
		return b58encode_check(b'\x00' + ripe)
```

**Comment by Dolantinlist** [comment]
涉及到的对EdgenceChain的改动见https://github.com/EdgeIntelligenceChain/EdgenceChain/tree/liuying_client_func
对EdgenceChain的更新有以下几点：

1）为Message增加OutPoint结构
2）修改Transaction中交易验证部分原有的bug
3)  为处理交易验证中的公钥不匹配问题，Wallet.pubkey_to_address(txin.unlock_pk))返回值为"b'1M32gppnnKfCcedHq3weaAagKU7Ppt6KFD'"， 而utxo.to_address值为”1M32gppnnKfCcedHq3weaAagKU7Ppt6KFD“， 采取了正则匹配处理，提取"b'1M32gppnnKfCcedHq3weaAagKU7Ppt6KFD'"中的有效部分用于比较。
pubkey_as_addr = re.findall('b\'(.+?)\'', Wallet.pubkey_to_address(txin.unlock_pk))[0]

**Comment by Dolantinlist** [comment]
当前进展同步：

EdgeHand: 由于merge_failure-wolfbrother分支在修改后出现了别的问题，所以我选择了对liuying_add_func进行重新调整和封装，去除了对EdgeHand的命令行调用，改用main.py测试。测试代码见main.py，已加注释说明。
https://github.com/EdgeIntelligenceChain/EdgeHand/tree/liuying_add_func

EdgenceChain: liuying_client_func 分支 移除了交易验证确认相关代码。同时，因为对EdgeHand的代码进行了调整，所以交易验证的时候不再需要对地址进行正则匹配。https://github.com/EdgeIntelligenceChain/EdgenceChain

测试情况：
依次运行主链及客户端的main.py，余额查询、发送交易、交易状态查询功能均无误。但主链会在接收到交易之后无法正常打包，交易永远停留在mempool中。主链日志如下：

[2019-03-24 23:15:12,690][Consensus:29] INFO [consensus] mining +++ 4500001
[2019-03-24 23:15:13,590][Consensus:40] INFO [consensus] mining block found! 14 s - 342 KH/s - 000001007cd18fd12b6c0a220770b47dd43f580f25edd566301cf2405a727653
[2019-03-24 23:15:13,590][Block:187] INFO [p2p] already in another validate_block process
[2019-03-24 23:15:13,658][Block:179] INFO [ds] fees for 1 non-coinbase transactions in this block: 4999999890
[2019-03-24 23:15:13,658][TCPserver:305] INFO [p2p] subsidy and fees of this block are not right, so discard this block and return.
[2019-03-24 23:15:13,659][Block:179] INFO [ds] fees for 0 non-coinbase transactions in this block: 0
[2019-03-24 23:15:13,659][Consensus:25] INFO [consensus] mining after block 000001ac04c38ec044626d8b38d51dca0425ad1d36942089f738a3998d3d4fcd
[2019-03-24 23:15:13,659][Consensus:29] INFO [consensus] mining +++ 1

**Comment by wolfbrother** [comment]
收到，挺好的。
目前存在两个问题：
+ 构建交易的过程里，没有交易费用和找零的概念。
+ 区块奖励和交易费计算不正确
   ``` python
     block.block_subsidy_fees != Block.get_block_subsidy(active_chain) + block.calculate_fees(utxo_set)
   ```
   其中概念参看： https://github.com/EdgeIntelligenceChain/EdgenceChain/issues/43#issuecomment-471239464
